name: ci
on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jdino/citest
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-actions@v5
        with:
          push: false
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}
